maquina_virtual_name   = "maq_linux"
maquina_virtual_admin_username = "administrador"
maquina_virtual_size = "Standard_DS1_v2"
maquina_virtual_os_disk_name = "MyOSDisk"
maquina_virtual_os_disk_storage_account_type = "Premium_LRS"
maquina_virtual_source_image_reference_publisher= "MicrosoftWindowsServer"
maquina_virtual_source_image_reference_offer= "WindowsServer"